### ISSUE TITLE
[CONT] Configure compatibility relationships

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#166]
## Content 📄

Configure in `config.yaml` the compatibility relationships between projects.

## Additional Information ℹ️

To make `project-a` and `project-b` appear as compatible, add a `compatibles` field to one of them, specifying the identifier of the other:

```yaml
projects:
  - id: 'project-a'
    repository: 'https://example.com/project-a.git'
    contact:
      name: 'Superman'
      email: 'superman@example.com'
  - id: 'project-b'
    repository: 'https://example.com/project-b.git'
    contact:
      name: 'Batman'
      email: 'batman@example.com'
    compatibles:
      - 'project-a'
```
