### ISSUE TITLE
[CONT] Configure the parent-child relationships

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#167]
## Content 📄

Configure the parent-child relationships between projects in [config.yaml](../blob/master/config.yaml) file .

## Additional Information ℹ️

To make `project-a` appear as parent of `project-b` , add a `parents` field to `project-b`, specifying `project-a`  as a parent:

```yaml
projects:
  - id: 'project-a'
    repository: 'https://example.com/project-a.git'
    contact:
      name: 'Superman'
      email: 'superman@example.com'
  - id: 'project-b'
    repository: 'https://example.com/project-b.git'
    contact:
      name: 'Batman'
      email: 'batman@example.com'
    parents:
      - 'project-a'
```
