### ISSUE TITLE
[CONT] Configure project contacts

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#168]
## Content 📄

The project contacts were configured with a script that, for a given project, defined the main contributor as the contact person.
We need to check whether the contacts are correct since some of these people are no longer working on the projects. 

## Additional Information ℹ️

The contacts are configured in the `config.yaml` file as follows:

```yaml
projects:
  - id: 'project-a'
    repository: 'https://example.com/project-a.git'
    contact:
      name: 'Superman'
      email: 'superman@example.com'
  - id: 'project-b'
    repository: 'https://example.com/project-b.git'
    contact:
      name: 'Batman'
      email: 'batman@example.com'
```
