### ISSUE TITLE
[CONT] Configure featured projects

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#169]
## Content 📄

The most relevant projects should be configured as featured to have greater visibility on the website.

## Additional Information ℹ️

To configure `project-a` as featured , add `featured: true` to it's configuration in the `config.yaml` file:

```yaml
projects:
  - id: 'project-a'
    repository: 'https://example.com/project-a.git'
    contact:
      name: 'Superman'
      email: 'superman@example.com'
    featured: true
```
