### ISSUE TITLE
[CONT] Configure project tags

### ISSUE THREAD

**Issue by vascoguita** [OHWR/ohwr.org#211]
## Content 📄

Configure the project tags in the [config.yaml](../blob/master/config.yaml) file.

## Additional Information ℹ️

To add new tag `Example Tag` to a project `Example Project`, add the tag to the `tags` list at the top of the [config.yaml](../blob/master/config.yaml) file and to the `tags` field of the project:

```yaml
tags:
  - 'Example Tag'
projects:
  - id: 'example-project'
    repository: 'https://example.com/example-project.git'
    contact:
      name: 'Superman'
      email: 'superman@example.com'
    tags:
      - 'Example Tag'
```
